### ISSUE TITLE
Is there a char_set? 

### ISSUE THREAD

**Issue by martinrode** [goccmack/gogll#16]
The Readme.md mentions a `char_lit` and `char_set`. But `char_set` seems undefined. How do I specify 'a'-'z' (a to z)?

**Comment by marius-dau** [comment]
Gogll's lexer generator was designed for Unicode input rather than ASCII. It therefore supports the Unicode character classes, letter, number, upcase and lowcase.

You could specify lowcase but that would accept all Unicode lower case characters. 

Gogll does not currently support the traditional character ranges, such as 'a'-'z'.
