### ISSUE TITLE
generate a parser for ASN1 grammar

### ISSUE THREAD

**Issue by adibrastegarnia** [goccmack/gogll#3]
I would like to know if I can use gogll to generate a parser from ASN.1 grammar from something like this:
[ASN.1 Grammar example](
https://raw.githubusercontent.com/cederberg/mibble/master/src/grammar/asn1.grammar)

What changes will be needed?

**Comment by goccmack** [comment]
@adibrastegarnia

The differences that I can see between the grammar accepted by gogll and the ASN.1 grammar are the following:

1. The production rule definition symbol for gogll is ':' while for ASN.1 it is '='.
2. Gogll uses unicode classes in the lexical specification instead of character ranges. 
3. Gogll's lexical specification syntax for optional and repeated strings is different to the ASN.1 syntax.
4. Gogll does not have a notation for optional and repeated strings in the syntax specification part of the input grammar. In a gogll grammar we write those as alternates of the production rule and use recursion to define repetition.

If you translate the ASN.1 grammar to the gogll syntax it will work. Several years ago I used gogll's predecessor gocc to generate a parser for email headers from the ASN.1 from RFC2822 (if I remember correctly).

**Comment by adibrastegarnia** [comment]
@goccmack 
Thanks for your response. I will give it a try and see how it goes and then open this issue again if it is needed.
